import { StyleSheet } from "react-native";
import { commonStyles } from "./CommonStyles";

export const homeStyles = (theme) => StyleSheet.create({
  container: {
    ...commonStyles.container(theme),
    paddingTop: 80,
    paddingBottom: 30,
    paddingHorizontal: 24,
    minHeight:'100%'
  },
  head: {
    flexDirection: 'row',
    justifyContent: "space-between",
    alignItems: 'center',
    marginBottom: 25,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.primaryColor + '20',
  },
  headIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  headText: {
    flexDirection: 'column',
    gap: 4
  },
  headIconText: {
    fontSize: 36,
    fontWeight: 'bold',
    paddingHorizontal: 12,
    color: theme.primaryColor,
    backgroundColor: theme.primaryColor + '15', 
    borderRadius: 50,
    width: 50,
    height: 50,
    textAlign: 'center',
    textAlignVertical: 'center',
    lineHeight: 46,
  },
  title: {
    fontSize: 22,
    color: theme.textColor + 'CC',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  name: {
    fontSize: 28,
    color: theme.primaryColor,
    fontWeight: '800', 
    textShadowColor: theme.primaryColor + '40',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  card: {
    backgroundColor: theme.cardColor,
    width: 120,
    height: 180,
    borderRadius: 14,
    padding: 10,
    marginBottom: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: theme.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: theme.primaryColor + '10', 
    transform: [{ scale: 1 }], 
  },
  img: {
    width: '100%',
    height: 90,
    borderRadius: 10,
    resizeMode: 'cover',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.primaryColor + '10',
  },
  cardContent: {
    width: '100%',
    alignItems: 'center',
  },
  cardtitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.cardTitle,
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  cardsubtitle: {
    fontSize: 12,
    color: theme.cardSubTitle,
    textAlign: 'center',
    opacity: 0.9,
  },
  button: {
    ...commonStyles.button(theme),
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginLeft: 8,
    borderRadius: 12,
    shadowColor: theme.primaryColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  buttonText: {
    ...commonStyles.buttonText(theme),
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  flatListContainer: {
    paddingBottom: 30,
  },
  flatListColumnWrapper: {
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  }
});